stages:
  - test

test:
  image: 
    name: cypress/base:16.14.2-slim
    entrypoint: ['']
  stage: test
  parallel: 3
  script:
    - npm ci
    - npm start & 
    - npx cypress run --env split=true --browser replay-chromium